### ISSUE TITLE
关于 ViewGroup 在 Fragment 切换时滑动的问题

### ISSUE THREAD

**Issue by niorgai** [gdutxiaoxu/TouchDemo#1]
你好, 我在郭霖的公众号上看到你的文章:  `ViewPager，ScrollView 嵌套ViewPager滑动冲突解决` , 之前我也遇到过这么问题, 所以来跟你分享一下我的解决方案:

既然你知道了是 Focus 的问题, 那在 ViewGroup 层去解决的话, 可以有两个方法:

* 重写 `requestFocus(int direction, Rect previouslyFocusedRect)` 方法, 直接 return. 

          @Override
          public boolean requestFocus(int direction, Rect previouslyFocusedRect) {
                return false;
          }

* ViewGroup 屏蔽焦点, `setDescendantFocusability(FOCUS_BLOCK_DESCENDANTS);`

这是我的解决方法, 因为没找到好一点的联系方式, 就在这里提个 issues 好了, 随时可以关闭.

**Comment by gdutxiaoxu** [comment]
好的，非常感谢

**Comment by gdutxiaoxu** [comment]
在ViewPagerActivity 里面的Fragment的代码中加入一下代码，可以阻止RecyclerView的子View 获得焦点，从而阻止RecyclerView 抢占位置。
```
 //     是为了确保mNoHorizontalScrollView他的子孙不能获得焦点
       mNoHorizontalScrollView.setDescendantFocusability(ViewGroup.FOCUS_BLOCK_DESCENDANTS);
```
详细代码见项目中的ListFragement

**Comment by niorgai** [comment]
呃..既然你也认可这个方法, 我关掉它吧..
